#pragma once

#define MAX_QUAD_COUNT 10
#define MAX_VERTEX_COUNT MAX_QUAD_COUNT * 4
#define MAX_VERTEX_INDEX_COUNT MAX_QUAD_COUNT * 6
#define MAX_EDGE_COUNT MAX_VERTEX_COUNT * (MAX_VERTEX_COUNT - 1) / 2
#define MAX_EDGE_INDEX_COUNT MAX_EDGE_COUNT

#define MAX_SELECT_DISTANCE_SQUARED 2000

#define ROOT 0
#define FIELD 1
#define SUB_FIELD 2
#define MODEL 3